---
# Source: helm for kubernetes/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: book-ee7ed86d          # Service name
  labels:
    app: book-ee7ed86d
spec:
  type: ClusterIP   # Service type (ClusterIP, NodePort, LoadBalancer)
  selector:
    app: book-ee7ed86d         # Matches Deployment labels
  ports:
    - protocol: TCP
      port: 3000         # Service port
      targetPort: 3000  # Target container port
